cache: bundler
before_install:
  - |
    export RVM_CURRENT=`rvm current|cut -c6-8`
    if [ "${RVM_CURRENT}" = "2.0" ] || \
       [ "${RVM_CURRENT}" = "2.1" ] || \
       [ "${RVM_CURRENT}" = "2.2" ]; then
      gem install bundler -v '< 2'
    fi

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.10
  - 2.5.9
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - jruby-9.2.17.0
  - jruby-head
  - ruby-head
  - truffleruby-head
jdk:
  - openjdk8
notifications:
  email:
    on_success: change
    on_failure: always
